Semisecure lower hashingcost
DOMjudge/domjudge pull request #1067
Opened 2021-04-25 18:35 UTC by mvr320

2021-04-25 18:40 UTC, nickygerritsen approved these changes

2021-04-26 11:25 UTC, nickygerritsen requested changes

2021-04-26 11:25 UTC, nickygerritsen commented on webapp/src/Command/ResetUserPasswordCommand.php
> +        ?string $name = null
we can just drop the name arg (and pass nothing to the parent)

2021-04-26 19:34 UTC, nickygerritsen approved these changes

2021-05-01 17:15 UTC, mvr320 commented
I found a bug so will first make tests before merging this.

2021-09-10 10:28 UTC, mvr320 commented
Some things have changed so if someone can check again that would be nice.

2021-09-11 10:02 UTC, merged