Judgedaemon sleep increase
DOMjudge/domjudge pull request #1189
Opened 2021-09-15 19:22 UTC by mvr320

Based on suggestion by @meisterT

2021-09-15 19:23 UTC, meisterT commented on judge/judgedaemon.main.php
> +// Both constants in miliseconds
nit: milliseconds

2021-09-15 19:23 UTC, meisterT commented on judge/judgedaemon.main.php
> +const INITIAL_WAITTIME =  100;
consider adding the suffix `_MS` to the variable name to make it easier to see the unit

2021-09-15 19:25 UTC, meisterT commented on judge/judgedaemon.main.php
> +        $waittime = $waittime*2>MAXIMAL_WAITTIME ? MAXIMAL_WAITTIME : $waittime*2;
I would rewrite this as:
```
$waittime = min(MAXIMAL_WAITTIME, $waittime*2);
```

2021-09-15 19:25 UTC, meisterT commented on judge/judgedaemon.main.php
> +        logmsg(LOG_NOTICE, "Waittime now: ".$waittime);
Remove debug message?

2021-09-15 19:38 UTC, thijskh requested changes

2021-09-15 19:38 UTC, thijskh commented on judge/judgedaemon.main.php
> +$waittime = INITIAL_WAITTIME;
Variable is not defined

2021-09-15 19:38 UTC, thijskh commented on judge/judgedaemon.main.php
> +            $waittime = INITIAL_WAITTIME;
Same as above

2021-09-15 20:08 UTC, mvr320 commented on judge/judgedaemon.main.php
> +        usleep($waittime);
I checked and you're indeed right.

2021-09-16 06:34 UTC, thijskh commented
This is getting quite complex with all the multiplication factors. Also usleep might not really sleep and can still cause cpu activity.

How about this simpler approach:
- define sleeptime as 100 ms
- if  sleeptime < 1 s, sleep for sleeptime ms with usleep()
- else sleep() for the floor of sleeptime/1M maxed to 5 s
- multiply sleeptime by two and retry
- when getting work reset sleeptime to initial

2021-09-16 19:17 UTC, meisterT approved these changes

2021-09-17 10:54 UTC, merged