Stress tests error
DOMjudge/domjudge pull request #1381
Opened 2021-12-04 13:41 UTC by vmcj

Currently we submit files which should throw an 400. This PR tries to remove these log lines from the symfony integration log so we can assume that every HTTP code above 299 should be handled.

I rather do this outside of the Makefile but this was the least amount of code needed.

2021-12-10 13:02 UTC, nickygerritsen approved these changes

2021-12-10 13:13 UTC, eldering commented on tests/Makefile
> +check-problems: test-normal test-fltcmp test-boolfind
`check-problems` should also be added to the `.PHONY` targets as it's not a real file that gets created.

2021-12-10 13:14 UTC, eldering requested changes
See comment about `check-problems` as PHONY target.

2021-12-11 10:22 UTC, eldering approved these changes

2021-12-11 17:10 UTC, merged