Split the problem text content from the problem in the database.
DOMjudge/domjudge pull request #2241
Opened 2023-11-24 14:02 UTC by nickygerritsen

This is to prepare for the next Doctrine release, which [doesn't allow partial queries anymore](https://www.doctrine-project.org/projects/doctrine-orm/en/2.17/reference/partial-objects.html). This is also to make it consistent with other blobs in the database like submission files and problem attachments.

This is preparation for #2069 where I will do a similar thing.

Besides this there is one more partial query, which I will remove in a separate PR.

I know changing database stuff just for the ORM is not something to do lightly, but I don't think we have any better way. And this actually improves queries in the places where we used partial queries before IMHO.

2023-11-24 14:39 UTC, vmcj commented on webapp/migrations/Version20231124133426.php
> +        return '';
Can you describe what is happening?

2023-11-24 14:41 UTC, vmcj commented on webapp/src/Entity/Problem.php
> +     * @return string|null
```suggestion
```

2023-11-24 14:43 UTC, vmcj requested changes
I'm not the target audience for this one

2024-01-12 09:46 UTC, nickygerritsen commented
I propose to merge this after the current contest 'season', unless others think we should do it before so we can test it?

2024-01-12 09:46 UTC, vmcj approved these changes

2024-01-12 20:14 UTC, merged