Fix num teams query for contests.
DOMjudge/domjudge pull request #923
Opened 2020-11-14 09:07 UTC by nickygerritsen

We can't load it in one query, since we will get data double if you add both a team directly and through a category.

Feels a bit ugly to do 3 queries, but the only other option I see would be to do a DISTINCT instead of a count and I think that is even slower.

2020-11-14 09:34 UTC, eldering commented
I think it would be better to just fetch all team ids and then do a unique count in code. That's only a single query and prevents a lot of duplicate and bulky query code.

2020-11-14 09:37 UTC, eldering requested changes
See my comment: let's not do 3 bulky SQL queries where one suffices.

2020-11-14 09:41 UTC, nickygerritsen commented
> See my comment: let's not do 3 bulky SQL queries where one suffices.

If you believe that is faster I can update to it. Will to this afternoon.

2020-11-14 10:16 UTC, eldering commented
> > See my comment: let's not do 3 bulky SQL queries where one suffices.
> 
> If you believe that is faster I can update to it. Will to this afternoon.

I'm not sure it's faster (although could be: the overhead of each query maybe be bigger than data transfer), but mostly it leads to cleaner code.

2020-11-14 10:26 UTC, nickygerritsen commented
Probably speed is not a real issue anyway, this page probably doesn’t contain a million contests and isn’t visited too often

2020-11-14 12:33 UTC, nickygerritsen commented
This seems to work just fine :)

2020-11-14 13:09 UTC, eldering approved these changes
Also looks fine to me.

2020-11-14 13:11 UTC, merged

2020-11-22 07:14 UTC, thijskh commented
Why is this not `COUNT(DISTINCT teamid)`?